version: '2'
services:
  api:
    build: .
    restart: always
    volumes:
      - .:/app/api
      - /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
